# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Sam/Documents/Vivado2015/Example27_Adder/Example27_Adder.cache/wt [current_project]
set_property parent.project_path C:/Users/Sam/Documents/Vivado2015/Example27_Adder/Example27_Adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib -sv C:/Users/Sam/Documents/Vivado2015/Example27_Adder/Example27_Adder.srcs/sources_1/new/Adder4a.sv
read_xdc C:/Users/Sam/Documents/Vivado2015/Example27_Adder/Example27_Adder.srcs/constrs_1/imports/.Xilinx/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Sam/Documents/Vivado2015/Example27_Adder/Example27_Adder.srcs/constrs_1/imports/.Xilinx/Nexys4DDR_Master.xdc]

synth_design -top Adder4a -part xc7a100tcsg324-1
write_checkpoint -noxdef Adder4a.dcp
catch { report_utilization -file Adder4a_utilization_synth.rpt -pb Adder4a_utilization_synth.pb }
