# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/2023Sam/Vivado2022/Codes/ping-pongText/ping-pong.srcs/sources_1/ip/Fudan320x320/Fudan320x320.xci
# IP: The module: 'Fudan320x320' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/2023Sam/Vivado2022/Codes/ping-pongText/ping-pong.srcs/sources_1/ip/Fudan320x320/Fudan320x320_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fudan320x320'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/2023Sam/Vivado2022/Codes/ping-pongText/ping-pong.srcs/sources_1/ip/Fudan320x320/Fudan320x320.xci
# IP: The module: 'Fudan320x320' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/2023Sam/Vivado2022/Codes/ping-pongText/ping-pong.srcs/sources_1/ip/Fudan320x320/Fudan320x320_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fudan320x320'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
