# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado/pic/pic.srcs/sources_1/ip/screen_pic/screen_pic.xci
# IP: The module: 'screen_pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado/pic/pic.srcs/sources_1/ip/screen_pic/screen_pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'screen_pic'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/vivado/pic/pic.srcs/sources_1/ip/screen_pic/screen_pic.xci
# IP: The module: 'screen_pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado/pic/pic.srcs/sources_1/ip/screen_pic/screen_pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'screen_pic'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
