# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/vivado/Nexys4DDR_Master.xdc

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet
